name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      is_installation:
        description: 'Run as installation (true/false)'
        required: false
        default: 'false'
        type: choice
        options:
          - 'false'
          - 'true'

jobs:
  deploy:
    uses: ArcoVoets/workflows/.github/workflows/deploy.yml@master
    with:
      is_installation: ${{ github.event_name == 'workflow_dispatch' && inputs.is_installation == 'true' || false }}
      php_version: '8.4'
      node_version: '22'
      database: 'mariadb'
      repository: ${{ github.repository }}
      branch: 'master'
      site_sub_domain: ${{ vars.site_sub_domain || '' }}
    secrets: inherit
