name: Test

on:
  push:
    branches:
      - '**'
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - '**'
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    uses: ArcoVoets/workflows/.github/workflows/test.yml@master
    with:
      php_version: '8.4'
      node_version: '24'
      database: 'mariadb'
